# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: coder <coder@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/14 01:15:33 by coder             #+#    #+#              #
#    Updated: 2022/09/14 01:39:45 by coder            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILENAME	= Bisseccao.c
NAME		= bissec

all : $(NAME)

$(NAME):
	gcc -Wall -Werror -Wextra -g -lm $(FILENAME) -o $(NAME)

clean:
	rm $(NAME)
re: clean all
	