# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: smodesto <smodesto@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/09/21 19:10:10 by smodesto          #+#    #+#              #
#    Updated: 2021/12/04 14:44:01 by smodesto         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILENAME = Sistema_eleicao
all:	
	g++  -g -Wall -Wextra -Werror $(FILENAME).cpp -o $(FILENAME)